// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace PBSpecFlow
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("AlwaysCheaperOnline", Description="\tIn order to avoid silly mistakes\r\n\tAs a math idiot\r\n\tI want to be told the sum o" +
        "f two numbers", SourceFile="AlwaysCheaperOnline.feature", SourceLine=0)]
    public partial class AlwaysCheaperOnlineFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "AlwaysCheaperOnline.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "AlwaysCheaperOnline", "\tIn order to avoid silly mistakes\r\n\tAs a math idiot\r\n\tI want to be told the sum o" +
                    "f two numbers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void AddTwoNumbers(string language, string text, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "mytag"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add two numbers", @__tags);
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("I have a booking", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
 testRunner.When(string.Format("I navigate to UpsellSeatPage in this \'{0}\' language", language), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 10
 testRunner.Then(string.Format("the text will be \'{0}\' as expected", text), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add two numbers, CA", new string[] {
                "mytag"}, SourceLine=12)]
        public virtual void AddTwoNumbers_CA()
        {
#line 7
this.AddTwoNumbers("CA", "En línia, sempre és més econòmic", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add two numbers, CS", new string[] {
                "mytag"}, SourceLine=12)]
        public virtual void AddTwoNumbers_CS()
        {
#line 7
this.AddTwoNumbers("CS", "Online vždy levněji", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add two numbers, DA", new string[] {
                "mytag"}, SourceLine=12)]
        public virtual void AddTwoNumbers_DA()
        {
#line 7
this.AddTwoNumbers("DA", "Altid billigere online", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add two numbers, DE", new string[] {
                "mytag"}, SourceLine=12)]
        public virtual void AddTwoNumbers_DE()
        {
#line 7
this.AddTwoNumbers("DE", "Online immer günstiger", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add two numbers, EL", new string[] {
                "mytag"}, SourceLine=12)]
        public virtual void AddTwoNumbers_EL()
        {
#line 7
this.AddTwoNumbers("EL", "Πάντα πιο φθηνά online", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add two numbers, EN", new string[] {
                "mytag"}, SourceLine=12)]
        public virtual void AddTwoNumbers_EN()
        {
#line 7
this.AddTwoNumbers("EN", "Always cheaper online", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add two numbers, ES", new string[] {
                "mytag"}, SourceLine=12)]
        public virtual void AddTwoNumbers_ES()
        {
#line 7
this.AddTwoNumbers("ES", "Más económico en línea", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add two numbers, FR", new string[] {
                "mytag"}, SourceLine=12)]
        public virtual void AddTwoNumbers_FR()
        {
#line 7
this.AddTwoNumbers("FR", "Toujours moins cher en ligne !", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add two numbers, HU", new string[] {
                "mytag"}, SourceLine=12)]
        public virtual void AddTwoNumbers_HU()
        {
#line 7
this.AddTwoNumbers("HU", "Online mindig olcsóbb", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add two numbers, IT", new string[] {
                "mytag"}, SourceLine=12)]
        public virtual void AddTwoNumbers_IT()
        {
#line 7
this.AddTwoNumbers("IT", "Sempre più economico online", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add two numbers, NL", new string[] {
                "mytag"}, SourceLine=12)]
        public virtual void AddTwoNumbers_NL()
        {
#line 7
this.AddTwoNumbers("NL", "Altijd goedkoper online", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add two numbers, PL", new string[] {
                "mytag"}, SourceLine=12)]
        public virtual void AddTwoNumbers_PL()
        {
#line 7
this.AddTwoNumbers("PL", "Zawsze taniej przez Internet", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add two numbers, PT", new string[] {
                "mytag"}, SourceLine=12)]
        public virtual void AddTwoNumbers_PT()
        {
#line 7
this.AddTwoNumbers("PT", "Sempre mais barato online", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
